# Introduction {#ch:intro}

In this world, people wish to understand the future development of different events. For example, residents want to know tomorrow's weather and temperatures to decide what kind of clothes they need to choose. Securities investors want to know the future price trend of securities in order to formulate a suitable investment portfolio. Unfortunately, it is very difficult for humans to predict the future because uncertainty is a universal feature of this world. Although we have a variety of ways to predict future events, such as building suitable time series models based on past information, then predicting future trends over time, none of these methods provides absolutely accurate future predictions. The limitations are that, first of all, various activities and phenomena in the real world are difficult to be perfectly represented by mathematical models, especially humanistic phenomena such as the purchase of lottery tickets (the outcome of the lottery is random). Although there are some natural phenomena, they have certain rules to follow, such as temperature have seasonal changes, so it is very difficult to establish prediction models for them. Second, human cognition is limited. For the event, people cannot collect and obtain all of the information for the relevant factors. Because of these limitations, using these methods to make predictions must not be absolutely accurate. For now, to accurately forecast future is still a difficult task, but as more and more prediction methods and models are developed, forecasters can use them to get what they want. The following problem is how to evaluate these models because choosing the correct assessment method can effectively compare the accuracy of forecast results by using different models, then the forecaster can obtain the most suitable prediction model. 

In choosing the forecast method, point forecast is the most commonly used. But forecasts should be probabilistic (@GK14) and point estimation gradually transform to distribution estimation (@S75). Therefore, interval forecasts and probabilistic are being used more and more frequently. In the past few decades, the interval forecasts and probabilistic forecasts have a very important development and are attracting more and more attention. Probabilistic prediction is a method to forecast future uncertain events and development by generating probability prediction distribution. Base on the available information set, to maximize the sharpness of prediction distribution and subject to calibrate (@GK14). Comparing the point forecasts can produce a single point result, such as predicted a stock price in the next day, probabilistic prediction can supply more information to the forecaster by assigning a probability distribution to each future possible outcome as supplying the probabilistic distribution on different prices on the second day. Obviously, probabilistic forecasting has more obvious advantages than point forecasting, so more and more organizations and individuals begin to use probability prediction instead of point prediction to carry out the future in many fields, such as finance, weather, medicine etc. In the @R16 paper, it discussed five potential predictors who have a need for probability forecasts. 

For evaluating the accuracy of point forecast results, the common ways are to calculate the forecast errors, scale-dependent errors (as Mean absolute error, Root mean squared error), percentage errors (as Mean absolute percentage error) or scale errors (as the mean absolute scaled error) (@RA18). The traditional evaluation methods of point prediction cannot effectively evaluate the results of probabilistic prediction. Because if we want to evaluate the probability prediction effectively, we should not only evaluate the sharpness of the prediction distribution but also evaluate its calibration. For evaluating the result of interval forecasts and probabilistic forecasts, scoring rules is a very effective method. It can evaluate the sharpness of the prediction of distribution while assessing calibration. At present, scoring rules are mainly used in weather forecasting system. They provide such an assessment by giving a numerical score based on probability and actual observation (@W96) and proper scoring rules encourage the forecaster to conduct careful assessment and honesty (@GR07). 

The selection and introduction of the scoring rules are placed in chapter 2. This chapter describes in detail two different types of scores, interval scores and distribution scores. In addition, four types of scoring rules that were used for subsequent case studies were specified. The third chapter mainly describes all the time series models used in this paper. For each model, their main characteristics and how to make predictions are introduced in detail in this chapter. The methods and tools used to select for them are also illustrated. Chapters 4 and 5 are case studies 1 and 2, respectively. In Case Study 1, financial data (ASX200) was used. Data were analyzed and predicted using predictive models, and the results were scored separately. In order to observe the different score performance of the prediction results using different prediction models. In Chapter 5, we make separate predictions for all the time series in the M3 datasets and evaluate the forecast results. We mainly examine how the scoring rules perform in different types of time series. the conclusion and future discussion are given in Chapter 6.
