# Conclusion and future discussion

## Conclusion

As a common means to evaluate interval prediction and probability prediction, scoring rules are widely used. The score of the prediction is scored by evaluating the sharpness of the prediction result and the calibration. This article presents two different types of scores, interval scores and distribution scores. Interval scores are used to score interval predictions, commonly used by Winkler loss scoring rule. According to its formula, this scoring rule is based on whether observations are given a rating within the prediction interval, if the observation misses the interval, the score will depend on $\alpha$. For distribution scores, this paper mainly selects three scoring rules, Logarithmic score rules, Continuous Ranked Probability Score and Dawid-Sebastianti score. This article uses them all based on Gaussian prediction distribution LogS and DSS scoring rules can directly transfer data because of its own formula, so you don't have to worry about standardization when using it. While for the CRPS scoring rule, although it is necessary to pay attention to the standardized result when it is used and it is difficult to evaluate the prediction result with a complicated distribution, it can be easily used because it does not need too much consideration of the characteristics of the prediction distribution. Another concept that needs attention is the difference between the confidence interval and the prediction interval, which are often mistaken for the same. What is used when predicting using the predictive model is the prediction interval.

Regarding the prediction model used, because different data were used in the two case study, different models were used in the different case study. For case study one using financial data, the ARIMA model that can be used to analyze and forecast stationary time series, and the GRACH model that can well explain the volatility clusters characteristics of financial time series are used. In case study 2, because the M3 dataset has a large number of time series in different fields, multiple types of time series models can be used. However, because of this, standardization issues need to be noted when comparing the final score results. Here ARIMA, ETS and random walk models are used.

Through the summary of case study one, the scoring rules were used to evaluate the univariate financial time series. After evaluating the results of the interval prediction and probability prediction generated by the two different models, I found that comparing the results by using ARIMA model, the GARCH model has good performance both in interval prediction and probabilistic prediction. However, in the interval prediction, the score obtained by the same GARCH model is high in the case of high prediction interval level, indicating that its prediction result is not ideal. At the low prediction interval level, it has a good performance. For case study two, we mainly understand how to use scoring rules to evaluate the prediction results of different types of time series. Through the use of an automatic model-finding program, all time series in the M3 datasets were modelled and predicted separately, and then different prediction rules were used to evaluate separately by using different scoring rules.  For the results, both the interval prediction and the probability prediction, the two models used for comparison have a similar prediction performance. According to the results of the scores, there is not a big difference in the predictions they provide, and their appearances have their own advantages in different predictions.

The predictive model typically provides an estimate of the forecast distribution for each forecast range, or at least one forecast interval. As a means to assess the accuracy of the prediction results, the scoring rules can be intuitively given a numerical rating result for the prediction results. Especially in applications for probabilistic prediction, the scoring rules can simultaneously evaluate the predicted distribution sharpness and calibration. The predictors can use these results to determine whether the prediction results are reliable and whether the selected prediction model is appropriate.


## Future discussion

For probabilistic prediction and interval prediction, univariate time series are mainly used for analysis and prediction. However, in many cases, the development of an event is not only influenced by its own changes, but other events also affect the observed events. Therefore, it is important to study the multivariate time series model and use this model to make interval and probability prediction. At the same time, we need to study new scoring rules for this situation to evaluate the accuracy of the prediction.
