# References

  * Edgar C. Merkle, Mark Steyvers (2013) Choosing a Strictly Proper Scoring Rule. *Decision Analysis* 10(4):292-304.

  * Gneiting T, Balabdaoui F, Raftery AE. (2007). Probabilistic forecasts, calibration and sharpness. *J. R. Stat. Soc. B* 67:243–68

  * Gneiting, T., & Katzfuss, M. (2014). Probabilistic forecasting. *Annual Review of Statistics and Its Application*, 1(1), 125–151.

  * Gneiting T, Raftery AE. 2007. Strictly proper scoring rules, prediction, and estimation. *J. Am. Stat. Assoc.* 102:359–378

  * Hersbach, H. (2000), “Decomposition of the Continuous Ranked Probability Score for Ensemble Prediction Systems,” *Weather and Forecasting*, 15(5),559–570.

  * Hyndman, R. J. (2018). forecast: Forecasting functions for time series and linear models (R package version 8.3). https://CRAN.R-project.org/package=forecast

  * Hyndman, R. J., & Athanasopoulos, G. (2018). Forecasting: principles and practice. 2nd ed., Melbourne, Australia: OTexts. https://OTexts.org/fpp2/

  * Hyndman, R. J.(2018).Data from the M-Competitions (R package version 2.7). https://CRAN.R-project.org/package=Mcomp

  * Jordan. A., Krueger. F., Lerch. S. (2017). Scoring Rules for Parametric and Simulated Distribution Forecasts. (R package version 0.9.4).  https://CRAN.R-project.org/package=scoringRules

  * Matheson, J. E., and Winkler, R. L. (1976), “Scoring Rules for Continuous Probability Distributions,” *Management Science*, 22, 1087–1096.

  * Peirolo. R. (2010). Information gain as a score for probabilistic forecasts. *Meteorological Applications* 03/2011, Vol.18(1), pp.9-17

  * Raftery, A. E. (2016). Use and communication of probabilistic forecasts. *Statistical Analysis and Data Mining: The ASA Data Science Journal*, 9(6), 397–410.

  * Roulston, M. S., and Smith, L. A. (2002), “Evaluating Probabilistic Forecasts Using Information Theory,” *Monthly Weather Review*, 130(6), 1653–1660.
  
  * Wuertz. D. (2017). Rmetrics - Autoregressive Conditional Heteroskedastic Modelling (R package version 3042.83). https://CRAN.R-project.org/package=fGarch

  * Wickham. H. (2017). Easily Install and Load the 'Tidyverse'. (R package version 1.2.1).  https://CRAN.R-project.org/package=tidyverse

